import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';



@NgModule({
  declarations: [],
  imports: [
    CommonModule
  ]
})
export class AccountModule { }
// src/app/model/account.model.ts

export interface Account {
  id?: number;             // optional because backend generates it
  name: string;
  dob: string;             // keep as string, parse to Date if needed
  age: number;
  occupation: string;

  aadharNumber: string;
  pan: string;

  accountNumber?: string;  // optional, may be auto-generated by backend
  balance: number;         // default 0.0 in backend
  verifiedMatrix: boolean; // true/false from backend
}
